[package]
name = "install_reason_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
colored = "2.1.0"
dialoguer = "0.11.0"
dirs = "5.0.1"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
